name: Deploy# Actions名称
on:
  push: # 监听调用时机为push事件
    branches: ["master"] # 监听master分支
jobs:
  build:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: 拉取代码 # 步骤名字
        uses: actions/checkout@master # 使用 actions/checkout 库拉取最新源码

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 项目安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 打包构建组件库文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build:uidocs

      - name: 打包构建模板文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build:docs

      - name: 部署组件库文档到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "modules/wm-taro-design/doc_build/"
          target: "/opt/project/.temp_uidocs/"
          rm: true
          strip_components: 3

      - name: 部署模板文档到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "modules/wm-taro-template-docs/dist/"
          target: "/opt/project/.temp_docs/"
          rm: true
          strip_components: 3

      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p /opt/project/frontDoc/wm-taro
            mkdir -p /opt/project/frontDoc/wm-taro-design
            rm -rf /opt/project/frontDoc/wm-taro/*
            rm -rf /opt/project/frontDoc/wm-taro-design/*
            cp -rf /opt/project/.temp_docs/*    /opt/project/frontDoc/wm-taro/
            cp -rf /opt/project/.temp_uidocs/*  /opt/project/frontDoc/wm-taro-design/

      - run: echo "项目部署完成！"
